### ISSUE TITLE
微信小程序环境运行中断

### ISSUE THREAD

**Issue by BenjaminCCG** [ttk-cli/uni-vue3-vite-ts-pinia#54]
控制台报错提示
```
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: EBUSY: resource busy or locked, lstat 'E:\DumpStack.log.tmp'
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (file:///E:/webExe/uni-vue3-vite-ts-pinia/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/watch.js:4246:10)
    at ReaddirpStream.NodeFsHandler._boundHandleError (file:///E:/webExe/uni-vue3-vite-ts-pinia/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/watch.js:2720:43)
    at ReaddirpStream.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4082,
  code: 'EBUSY',
  syscall: 'lstat',
  path: 'E:\\DumpStack.log.tmp'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

该如何解决

**Comment by Allen-1998** [comment]
本项目使用 npm， node 16.x，删除依赖重新安装试试看呢
